---
abstract: 'Generate data for Data Matrix barcodes'
author:
  - 'Mons Anderson C<< <inthrax@gmail.com> >> (GD::Barcode::DataMatrix at L<http://code.google.com/p/perl-ex/>, from which this distribution originates)'
  - 'Mark A. Stratman <stratman@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Barcode-DataMatrix
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.15
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/mstratman/Barcode-DataMatrix.git
version: 0.04
